# WeatherPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
from scipy.stats import linregress

# Import API key
from api_keys import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

## Generate Cities List

In [2]:
# List for holding lat_lngs and cities
lat_lngs = []
cities = []

# Create a set of random lat and lng combinations
lats = np.random.uniform(lat_range[0], lat_range[1], size=1500)
lngs = np.random.uniform(lng_range[0], lng_range[1], size=1500)
lat_lngs = zip(lats, lngs)

# Identify nearest city for each lat, lng combination
for lat_lng in lat_lngs:
    city = citipy.nearest_city(lat_lng[0], lat_lng[1]).city_name
    
    # If the city is unique, then add it to a our cities list
    if city not in cities:
        cities.append(city)

# Print the city count to confirm sufficient count
len(cities)

614

### Perform API Calls
* Perform a weather check on each city using a series of successive API calls.
* Include a print log of each city as it'sbeing processed (with the city number and city name).

In [3]:
city_name = []
lat = []
long = []
max_temp = []
humidity = []
cloudiness = []
wind_speed = []
country = []
date = []

print("Beginning Data Retrieval ")
print("-----------------------------")

base_url = "http://api.openweathermap.org/data/2.5/weather?"
units = "imperial"
query_url = f"{base_url}appid={weather_api_key}&units={units}&q="

i = 0
j = 1

for city in cities:   
    try:
        response = requests.get(query_url + city).json()
        city_name.append(response["name"])
        lat.append(response["coord"]["lat"])
        long.append(response["coord"]["lon"])        
        max_temp.append(response['main']['temp_max'])  
        humidity.append(response["main"]["humidity"])        
        cloudiness.append(response["clouds"]["all"])
        wind_speed.append(response["wind"]["speed"])
        country.append(response["sys"]["country"])
        date.append(response["dt"])            
        print(f"Processing Record {i} of Set {j} : {city}") 
        i = i + 1
        if i > 49:
            i = 0
            j = j + 1
            
    except(KeyError, IndexError):
        print("City not found. Skipping...")

print("-----------------------------")
print("Data Retrieval Complete")

Beginning Data Retrieval
-----------------------------
Processing Record 0 of Set 1 : asau
Processing Record 1 of Set 1 : cape town
City not found. Skipping...
Processing Record 2 of Set 1 : komsomolskiy
Processing Record 3 of Set 1 : plover
Processing Record 4 of Set 1 : aswan
Processing Record 5 of Set 1 : busselton
Processing Record 6 of Set 1 : port alfred
Processing Record 7 of Set 1 : biak
Processing Record 8 of Set 1 : mahebourg
Processing Record 9 of Set 1 : bodaybo
Processing Record 10 of Set 1 : bambous virieux
Processing Record 11 of Set 1 : pedasi
Processing Record 12 of Set 1 : sakete
Processing Record 13 of Set 1 : general roca
Processing Record 14 of Set 1 : rikitea
City not found. Skipping...
Processing Record 15 of Set 1 : mahanoro
Processing Record 16 of Set 1 : mataura
Processing Record 17 of Set 1 : ushuaia
Processing Record 18 of Set 1 : adelaide
Processing Record 19 of Set 1 : karaton
Processing Record 20 of Set 1 : rio gallegos
Processing Record 21 of Set 1 : san patricio
Processing Record 22 of Set 1 : victoria
Processing Record 23 of Set 1 : kapaa
Processing Record 24 of Set 1 : lebu
Processing Record 25 of Set 1 : kosice
Processing Record 26 of Set 1 : calabozo
Processing Record 27 of Set 1 : albany
Processing Record 28 of Set 1 : soyo
City not found. Skipping...
Processing Record 29 of Set 1 : port elizabeth
Processing Record 30 of Set 1 : conselheiro pena
Processing Record 31 of Set 1 : riyadh
City not found. Skipping...
Processing Record 32 of Set 1 : arraial do cabo
Processing Record 33 of Set 1 : matara
Processing Record 34 of Set 1 : avarua
Processing Record 35 of Set 1 : vao
Processing Record 36 of Set 1 : bluff
Processing Record 37 of Set 1 : aksha
Processing Record 38 of Set 1 : nador
Processing Record 39 of Set 1 : geraldton
Processing Record 40 of Set 1 : twentynine palms
Processing Record 41 of Set 1 : syracuse
Processing Record 42 of Set 1 : bengkulu
City not found. Skipping...
Processing Record 43 of Set 1 : iqaluit
Processing Record 44 of Set 1 : butaritari
Processing Record 45 of Set 1 : deputatskiy
Processing Record 46 of Set 1 : saint-augustin
Processing Record 47 of Set 1 : hermanus
Processing Record 48 of Set 1 : mar del plata
Processing Record 49 of Set 1 : wajir
Processing Record 0 of Set 2 : punta arenas
Processing Record 1 of Set 2 : atuona
Processing Record 2 of Set 2 : kwinana
Processing Record 3 of Set 2 : namatanai
Processing Record 4 of Set 2 : tessalit
Processing Record 5 of Set 2 : grafton
Processing Record 6 of Set 2 : damara
Processing Record 7 of Set 2 : ixtapa
Processing Record 8 of Set 2 : labuhan
Processing Record 9 of Set 2 : ancud
Processing Record 10 of Set 2 : castro
Processing Record 11 of Set 2 : izmaylovo
Processing Record 12 of Set 2 : jamestown
Processing Record 13 of Set 2 : tuktoyaktuk
Processing Record 14 of Set 2 : kotovsk
Processing Record 15 of Set 2 : tilichiki
Processing Record 16 of Set 2 : sisimiut
Processing Record 17 of Set 2 : vaini
Processing Record 18 of Set 2 : hithadhoo
Processing Record 19 of Set 2 : dikson
Processing Record 20 of Set 2 : thompson
Processing Record 21 of Set 2 : ponta delgada
Processing Record 22 of Set 2 : comodoro rivadavia
Processing Record 23 of Set 2 : chokurdakh
Processing Record 24 of Set 2 : qaanaaq
City not found. Skipping...
City not found. Skipping...
Processing Record 25 of Set 2 : torbay
Processing Record 26 of Set 2 : doka
Processing Record 27 of Set 2 : codrington
Processing Record 28 of Set 2 : hobart
Processing Record 29 of Set 2 : saint-philippe
City not found. Skipping...
Processing Record 30 of Set 2 : thinadhoo
Processing Record 31 of Set 2 : hilo
City not found. Skipping...
Processing Record 32 of Set 2 : madimba
City not found. Skipping...
Processing Record 33 of Set 2 : bealanana
Processing Record 34 of Set 2 : hami
Processing Record 35 of Set 2 : tateyama
Processing Record 36 of Set 2 : pagudpud
Processing Record 37 of Set 2 : valdivia
Processing Record 38 of Set 2 : ambilobe
Processing Record 39 of Set 2 : khani
Processing Record 40 of Set 2 : east london
Processing Record 41 of Set 2 : fairbanks
Processing Record 42 of Set 2 : sandur
Processing Record 43 of Set 2 : te anau
Processing Record 44 of Set 2 : bloomington
Processing Record 45 of Set 2 : airai
Processing Record 46 of Set 2 : ubinskoye
Processing Record 47 of Set 2 : telimele
Processing Record 48 of Set 2 : yellowknife
Processing Record 49 of Set 2 : guerrero negro
Processing Record 0 of Set 3 : fare
City not found. Skipping...
Processing Record 1 of Set 3 : broome
Processing Record 2 of Set 3 : lagoa
Processing Record 3 of Set 3 : alofi
Processing Record 4 of Set 3 : gat
Processing Record 5 of Set 3 : salalah
Processing Record 6 of Set 3 : peleduy
Processing Record 7 of Set 3 : mecca
Processing Record 8 of Set 3 : chapais
Processing Record 9 of Set 3 : okha
Processing Record 10 of Set 3 : cortes
Processing Record 11 of Set 3 : taltal
City not found. Skipping...
Processing Record 12 of Set 3 : bonavista
Processing Record 13 of Set 3 : port blair
Processing Record 14 of Set 3 : gweta
Processing Record 15 of Set 3 : egvekinot
Processing Record 16 of Set 3 : mandal
Processing Record 17 of Set 3 : adrar
Processing Record 18 of Set 3 : paita
Processing Record 19 of Set 3 : kodiak
Processing Record 20 of Set 3 : kutum
Processing Record 21 of Set 3 : bosaso
Processing Record 22 of Set 3 : mount isa
Processing Record 23 of Set 3 : hit
Processing Record 24 of Set 3 : santa cruz
Processing Record 25 of Set 3 : noumea
City not found. Skipping...
Processing Record 26 of Set 3 : upernavik
Processing Record 27 of Set 3 : longyearbyen
Processing Record 28 of Set 3 : pevek
Processing Record 29 of Set 3 : coihaique
Processing Record 30 of Set 3 : tasiilaq
Processing Record 31 of Set 3 : sabang
Processing Record 32 of Set 3 : la baneza
Processing Record 33 of Set 3 : lubumbashi
Processing Record 34 of Set 3 : xingcheng
Processing Record 35 of Set 3 : ballina
Processing Record 36 of Set 3 : bubaque
Processing Record 37 of Set 3 : tiznit
Processing Record 38 of Set 3 : norman wells
Processing Record 39 of Set 3 : pafos
City not found. Skipping...
Processing Record 40 of Set 3 : mount gambier
Processing Record 41 of Set 3 : moussoro
Processing Record 42 of Set 3 : nanortalik
Processing Record 43 of Set 3 : tiksi
Processing Record 44 of Set 3 : dzhebariki-khaya
Processing Record 45 of Set 3 : flinders
Processing Record 46 of Set 3 : parabel
Processing Record 47 of Set 3 : chengde
Processing Record 48 of Set 3 : grindavik
Processing Record 49 of Set 3 : new norfolk
Processing Record 0 of Set 4 : hamilton
Processing Record 1 of Set 4 : bredasdorp
Processing Record 2 of Set 4 : oum hadjer
Processing Record 3 of Set 4 : sao joao da barra
Processing Record 4 of Set 4 : songea
Processing Record 5 of Set 4 : vestmannaeyjar
Processing Record 6 of Set 4 : japura
Processing Record 7 of Set 4 : college
Processing Record 8 of Set 4 : alice springs
City not found. Skipping...
Processing Record 9 of Set 4 : megion
Processing Record 10 of Set 4 : manokwari
Processing Record 11 of Set 4 : barrow
Processing Record 12 of Set 4 : anloga
Processing Record 13 of Set 4 : cayenne
Processing Record 14 of Set 4 : severo-kurilsk
City not found. Skipping...
Processing Record 15 of Set 4 : padang
Processing Record 16 of Set 4 : moosomin
Processing Record 17 of Set 4 : methoni
Processing Record 18 of Set 4 : faanui
Processing Record 19 of Set 4 : chilmari
Processing Record 20 of Set 4 : manacapuru
City not found. Skipping...
Processing Record 21 of Set 4 : puerto ayora
Processing Record 22 of Set 4 : sioux lookout
Processing Record 23 of Set 4 : provideniya
City not found. Skipping...
Processing Record 24 of Set 4 : conway
Processing Record 25 of Set 4 : lardos
Processing Record 26 of Set 4 : cervo
Processing Record 27 of Set 4 : sao filipe
Processing Record 28 of Set 4 : carnarvon
Processing Record 29 of Set 4 : yulara
Processing Record 30 of Set 4 : fortuna
Processing Record 31 of Set 4 : port-gentil
City not found. Skipping...
Processing Record 32 of Set 4 : botwood
Processing Record 33 of Set 4 : constitucion
Processing Record 34 of Set 4 : hobyo
Processing Record 35 of Set 4 : dong hoi
Processing Record 36 of Set 4 : luderitz

Processing Record 37 of Set 4 : cherskiy
Processing Record 38 of Set 4 : bilma
Processing Record 39 of Set 4 : phuket
Processing Record 40 of Set 4 : huangyan
Processing Record 41 of Set 4 : fort nelson
Processing Record 42 of Set 4 : blyth
Processing Record 43 of Set 4 : kazerun
Processing Record 44 of Set 4 : takaka
Processing Record 45 of Set 4 : esperance
Processing Record 46 of Set 4 : kouango
City not found. Skipping...
Processing Record 47 of Set 4 : lieksa
Processing Record 48 of Set 4 : lemgo
Processing Record 49 of Set 4 : pachmarhi
Processing Record 0 of Set 5 : saint joseph
Processing Record 1 of Set 5 : port-cartier
Processing Record 2 of Set 5 : georgetown
Processing Record 3 of Set 5 : iisalmi
Processing Record 4 of Set 5 : souillac
Processing Record 5 of Set 5 : ishigaki
Processing Record 6 of Set 5 : cabo san lucas
Processing Record 7 of Set 5 : kavieng
Processing Record 8 of Set 5 : morehead
City not found. Skipping...
Processing Record 9 of Set 5 : kavaratti
Processing Record 10 of Set 5 : clyde river
Processing Record 11 of Set 5 : malumfashi
Processing Record 12 of Set 5 : koumac
Processing Record 13 of Set 5 : bathsheba
Processing Record 14 of Set 5 : paidha
Processing Record 15 of Set 5 : banjar
Processing Record 16 of Set 5 : khatanga
City not found. Skipping...
Processing Record 17 of Set 5 : marsh harbour
Processing Record 18 of Set 5 : tanda
Processing Record 19 of Set 5 : salym
Processing Record 20 of Set 5 : taraz
Processing Record 21 of Set 5 : mombetsu
Processing Record 22 of Set 5 : miandrivazo
Processing Record 23 of Set 5 : lata
Processing Record 24 of Set 5 : prieska
Processing Record 25 of Set 5 : srednekolymsk
Processing Record 26 of Set 5 : nacala
Processing Record 27 of Set 5 : ahipara
Processing Record 28 of Set 5 : caluquembe
Processing Record 29 of Set 5 : gelibolu
Processing Record 30 of Set 5 : caravelas
City not found. Skipping...
Processing Record 31 of Set 5 : muscat
Processing Record 32 of Set 5 : nikolskoye
Processing Record 33 of Set 5 : ca mau
Processing Record 34 of Set 5 : kismayo
Processing Record 35 of Set 5 : gagesti
Processing Record 36 of Set 5 : katsuura
Processing Record 37 of Set 5 : rawson
Processing Record 38 of Set 5 : port augusta
Processing Record 39 of Set 5 : gorgan
Processing Record 40 of Set 5 : bud
Processing Record 41 of Set 5 : ararat
City not found. Skipping...
Processing Record 42 of Set 5 : banfora
Processing Record 43 of Set 5 : vestmanna
Processing Record 44 of Set 5 : yatou
Processing Record 45 of Set 5 : tjaereborg
Processing Record 46 of Set 5 : diu
City not found. Skipping...
Processing Record 47 of Set 5 : sambava
Processing Record 48 of Set 5 : hasaki
Processing Record 49 of Set 5 : sosnovo-ozerskoye
Processing Record 0 of Set 6 : zhigansk
Processing Record 1 of Set 6 : san juan
Processing Record 2 of Set 6 : ulladulla
Processing Record 3 of Set 6 : narsaq
Processing Record 4 of Set 6 : kingaroy
Processing Record 5 of Set 6 : ketchikan
Processing Record 6 of Set 6 : zeya
Processing Record 7 of Set 6 : xining
Processing Record 8 of Set 6 : barabai
Processing Record 9 of Set 6 : grao mogol
Processing Record 10 of Set 6 : lalawigan
Processing Record 11 of Set 6 : maua
Processing Record 12 of Set 6 : bagan
Processing Record 13 of Set 6 : the valley
Processing Record 14 of Set 6 : biryusinsk
Processing Record 15 of Set 6 : corsicana
Processing Record 16 of Set 6 : polson
Processing Record 17 of Set 6 : bend
Processing Record 18 of Set 6 : sola
Processing Record 19 of Set 6 : san policarpo
Processing Record 20 of Set 6 : abu kamal
Processing Record 21 of Set 6 : southbridge
Processing Record 22 of Set 6 : gillette
Processing Record 23 of Set 6 : okhotsk
Processing Record 24 of Set 6 : paso de carrasco
Processing Record 25 of Set 6 : tucuman
Processing Record 26 of Set 6 : north bend
Processing Record 27 of Set 6 : hofn
Processing Record 28 of Set 6 : husavik
Processing Record 29 of Set 6 : emerald
Processing Record 30 of Set 6 : hokitika
Processing Record 31 of Set 6 : inuvik
Processing Record 32 of Set 6 : lithgow
Processing Record 33 of Set 6 : bintulu
Processing Record 34 of Set 6 : kholtoson
City not found. Skipping...
Processing Record 35 of Set 6 : babat
Processing Record 36 of Set 6 : leningradskiy
Processing Record 37 of Set 6 : kaitangata
Processing Record 38 of Set 6 : launceston
Processing Record 39 of Set 6 : bethel
Processing Record 40 of Set 6 : suez
Processing Record 41 of Set 6 : la ronge
Processing Record 42 of Set 6 : brovary
Processing Record 43 of Set 6 : buchanan
Processing Record 44 of Set 6 : ribeira grande
Processing Record 45 of Set 6 : puro
Processing Record 46 of Set 6 : banda aceh
Processing Record 47 of Set 6 : tuatapere
Processing Record 48 of Set 6 : poum
Processing Record 49 of Set 6 : angarsk
City not found. Skipping...
Processing Record 0 of Set 7 : saint-pierre
Processing Record 1 of Set 7 : aklavik
City not found. Skipping...
Processing Record 2 of Set 7 : nizhniy kislyay
Processing Record 3 of Set 7 : muros
Processing Record 4 of Set 7 : kruisfontein
Processing Record 5 of Set 7 : at-bashi
Processing Record 6 of Set 7 : cockburn town
Processing Record 7 of Set 7 : ilulissat
Processing Record 8 of Set 7 : san quintin
Processing Record 9 of Set 7 : andenes
Processing Record 10 of Set 7 : bonthe
Processing Record 11 of Set 7 : vila velha
Processing Record 12 of Set 7 : waipawa
City not found. Skipping...
Processing Record 13 of Set 7 : mackay
Processing Record 14 of Set 7 : ibra
Processing Record 15 of Set 7 : nurota
Processing Record 16 of Set 7 : muroto
Processing Record 17 of Set 7 : qorveh
Processing Record 18 of Set 7 : rock sound
Processing Record 19 of Set 7 : udimskiy
Processing Record 20 of Set 7 : palmer
Processing Record 21 of Set 7 : klaksvik
Processing Record 22 of Set 7 : sept-iles
Processing Record 23 of Set 7 : naze
City not found. Skipping...
Processing Record 24 of Set 7 : odda
Processing Record 25 of Set 7 : beroroha
Processing Record 26 of Set 7 : yurga
Processing Record 27 of Set 7 : imbituba
City not found. Skipping...
Processing Record 28 of Set 7 : hammerfest
Processing Record 29 of Set 7 : beloha
Processing Record 30 of Set 7 : whitefish
Processing Record 31 of Set 7 : chikmagalur
Processing Record 32 of Set 7 : fayetteville
Processing Record 33 of Set 7 : luena
City not found. Skipping...
City not found. Skipping...
Processing Record 34 of Set 7 : belaya gora
Processing Record 35 of Set 7 : montemorelos
City not found. Skipping...
Processing Record 36 of Set 7 : manuk mangkaw
Processing Record 37 of Set 7 : gamba
Processing Record 38 of Set 7 : kapuskasing
Processing Record 39 of Set 7 : tabas
Processing Record 40 of Set 7 : luchegorsk
Processing Record 41 of Set 7 : wanaraja
Processing Record 42 of Set 7 : yumen
Processing Record 43 of Set 7 : birjand
Processing Record 44 of Set 7 : faya
Processing Record 45 of Set 7 : mosquera
Processing Record 46 of Set 7 : khasan
Processing Record 47 of Set 7 : hirado
City not found. Skipping...
Processing Record 48 of Set 7 : eregli
Processing Record 49 of Set 7 : grand forks
Processing Record 0 of Set 8 : havoysund
Processing Record 1 of Set 8 : nishihara
Processing Record 2 of Set 8 : kyren
Processing Record 3 of Set 8 : el dorado
Processing Record 4 of Set 8 : ulaangom
Processing Record 5 of Set 8 : aginskoye
Processing Record 6 of Set 8 : aksay
Processing Record 7 of Set 8 : saint george
Processing Record 8 of Set 8 : port lincoln
Processing Record 9 of Set 8 : los llanos de aridane
Processing Record 10 of Set 8 : talnakh
City not found. Skipping...
Processing Record 11 of Set 8 : elko
Processing Record 12 of Set 8 : skibbereen
Processing Record 13 of Set 8 : ust-kan
Processing Record 14 of Set 8 : carutapera
City not found. Skipping...
Processing Record 15 of Set 8 : nyurba
Processing Record 16 of Set 8 : tevaitoa
Processing Record 17 of Set 8 : toppenish
Processing Record 18 of Set 8 : corinto
Processing Record 19 of Set 8 : saskylakh
Processing Record 20 of Set 8 : sibu
Processing Record 21 of Set 8 : sur
Processing Record 22 of Set 8 : verkhnevilyuysk
Processing Record 23 of Set 8 : ponta do sol
Processing Record 24 of Set 8 : itarema
Processing Record 25 of Set 8 : kieta

Processing Record 26 of Set 8 : balykshi
City not found. Skipping...
Processing Record 27 of Set 8 : peniche
Processing Record 28 of Set 8 : vicksburg
Processing Record 29 of Set 8 : kitimat
Processing Record 30 of Set 8 : lorengau
Processing Record 31 of Set 8 : hualmay
Processing Record 32 of Set 8 : gogrial
Processing Record 33 of Set 8 : maningrida
Processing Record 34 of Set 8 : sumbe
Processing Record 35 of Set 8 : nenjiang
Processing Record 36 of Set 8 : khash
Processing Record 37 of Set 8 : bayan
Processing Record 38 of Set 8 : barinas
Processing Record 39 of Set 8 : berdigestyakh
Processing Record 40 of Set 8 : mollendo
Processing Record 41 of Set 8 : teutonia
Processing Record 42 of Set 8 : deniliquin
Processing Record 43 of Set 8 : sinnamary
Processing Record 44 of Set 8 : taua
Processing Record 45 of Set 8 : booue
Processing Record 46 of Set 8 : le vauclin
Processing Record 47 of Set 8 : kalispell
Processing Record 48 of Set 8 : portland
Processing Record 49 of Set 8 : sompeta
Processing Record 0 of Set 9 : ostrovnoy
Processing Record 1 of Set 9 : presidente franco
Processing Record 2 of Set 9 : charqueadas
Processing Record 3 of Set 9 : salinopolis
Processing Record 4 of Set 9 : acarigua
Processing Record 5 of Set 9 : dalbandin
Processing Record 6 of Set 9 : tighnabruaich
Processing Record 7 of Set 9 : beauvais
Processing Record 8 of Set 9 : paamiut
Processing Record 9 of Set 9 : inhambane
Processing Record 10 of Set 9 : hovd
Processing Record 11 of Set 9 : dunedin
Processing Record 12 of Set 9 : nanchang
City not found. Skipping...
Processing Record 13 of Set 9 : saint anthony
Processing Record 14 of Set 9 : point fortin
Processing Record 15 of Set 9 : la plaine
Processing Record 16 of Set 9 : chuy
Processing Record 17 of Set 9 : rio claro
Processing Record 18 of Set 9 : bowmore
Processing Record 19 of Set 9 : bogandinskiy
Processing Record 20 of Set 9 : arlit
Processing Record 21 of Set 9 : santa fe
Processing Record 22 of Set 9 : santa maria
Processing Record 23 of Set 9 : assiniboia
Processing Record 24 of Set 9 : kango
Processing Record 25 of Set 9 : baijiantan
Processing Record 26 of Set 9 : clinton
Processing Record 27 of Set 9 : coquimbo
Processing Record 28 of Set 9 : opuwo
Processing Record 29 of Set 9 : virginia beach
Processing Record 30 of Set 9 : mandera
Processing Record 31 of Set 9 : rojhan
Processing Record 32 of Set 9 : ngunguru
Processing Record 33 of Set 9 : korla
Processing Record 34 of Set 9 : cubuk
Processing Record 35 of Set 9 : fajardo
Processing Record 36 of Set 9 : little current
Processing Record 37 of Set 9 : moron
Processing Record 38 of Set 9 : sao jose da coroa grande
Processing Record 39 of Set 9 : lodja
Processing Record 40 of Set 9 : kalat
Processing Record 41 of Set 9 : buala
Processing Record 42 of Set 9 : corumba
Processing Record 43 of Set 9 : margate
Processing Record 44 of Set 9 : sorland
Processing Record 45 of Set 9 : kodar
City not found. Skipping...
Processing Record 46 of Set 9 : port hardy
City not found. Skipping...
Processing Record 47 of Set 9 : nouakchott
City not found. Skipping...
Processing Record 48 of Set 9 : rondonopolis
Processing Record 49 of Set 9 : cacapava do sul
Processing Record 0 of Set 10 : luorong
Processing Record 1 of Set 10 : griffith
Processing Record 2 of Set 10 : luzhou
City not found. Skipping...
Processing Record 3 of Set 10 : emba
Processing Record 4 of Set 10 : batemans bay
Processing Record 5 of Set 10 : isangel
Processing Record 6 of Set 10 : kysyl-syr
Processing Record 7 of Set 10 : jaisalmer
Processing Record 8 of Set 10 : gornopravdinsk
Processing Record 9 of Set 10 : laguna
Processing Record 10 of Set 10 : sao miguel do araguaia
Processing Record 11 of Set 10 : abonnema
Processing Record 12 of Set 10 : nara
City not found. Skipping...
Processing Record 13 of Set 10 : fuerte olimpo
Processing Record 14 of Set 10 : grosseto
Processing Record 15 of Set 10 : kiama
Processing Record 16 of Set 10 : kamina
Processing Record 17 of Set 10 : nuristan
Processing Record 18 of Set 10 : miyako
Processing Record 19 of Set 10 : pangoa
Processing Record 20 of Set 10 : sidmouth
Processing Record 21 of Set 10 : kathmandu
City not found. Skipping...
Processing Record 22 of Set 10 : barcelona
Processing Record 23 of Set 10 : talkha
Processing Record 24 of Set 10 : taoudenni
Processing Record 25 of Set 10 : maldonado
Processing Record 26 of Set 10 : vostok
Processing Record 27 of Set 10 : ayan
Processing Record 28 of Set 10 : santiago
Processing Record 29 of Set 10 : kahului
Processing Record 30 of Set 10 : dingle
Processing Record 31 of Set 10 : prince rupert
Processing Record 32 of Set 10 : uusikaupunki
Processing Record 33 of Set 10 : gizo
Processing Record 34 of Set 10 : panama city
Processing Record 35 of Set 10 : praya
Processing Record 36 of Set 10 : linguere
Processing Record 37 of Set 10 : cooma
Processing Record 38 of Set 10 : hirara
Processing Record 39 of Set 10 : vitim
Processing Record 40 of Set 10 : metro
Processing Record 41 of Set 10 : progreso
Processing Record 42 of Set 10 : nha trang
Processing Record 43 of Set 10 : qasigiannguit
Processing Record 44 of Set 10 : leh
Processing Record 45 of Set 10 : meulaboh
Processing Record 46 of Set 10 : pyapon
Processing Record 47 of Set 10 : yelan
Processing Record 48 of Set 10 : sabha
Processing Record 49 of Set 10 : maragogi
Processing Record 0 of Set 11 : lethem
Processing Record 1 of Set 11 : pisco
Processing Record 2 of Set 11 : shahpur
Processing Record 3 of Set 11 : makakilo city
City not found. Skipping...
Processing Record 4 of Set 11 : oktyabrskoye
Processing Record 5 of Set 11 : cidreira
City not found. Skipping...
Processing Record 6 of Set 11 : calvinia
Processing Record 7 of Set 11 : nizhniy baskunchak
Processing Record 8 of Set 11 : marawi
Processing Record 9 of Set 11 : churapcha
Processing Record 10 of Set 11 : beringovskiy
Processing Record 11 of Set 11 : shelburne
Processing Record 12 of Set 11 : sacel
Processing Record 13 of Set 11 : urucui
Processing Record 14 of Set 11 : edelira
Processing Record 15 of Set 11 : buin
Processing Record 16 of Set 11 : darnah
City not found. Skipping...
Processing Record 17 of Set 11 : port hedland
Processing Record 18 of Set 11 : tupik
Processing Record 19 of Set 11 : angoche
Processing Record 20 of Set 11 : kimberley
City not found. Skipping...
Processing Record 21 of Set 11 : oktyabrskiy
Processing Record 22 of Set 11 : kadoma
City not found. Skipping...
Processing Record 23 of Set 11 : natal
Processing Record 24 of Set 11 : senanga
Processing Record 25 of Set 11 : merauke
Processing Record 26 of Set 11 : kaeo
Processing Record 27 of Set 11 : russell
Processing Record 28 of Set 11 : hambantota
Processing Record 29 of Set 11 : yenagoa
Processing Record 30 of Set 11 : kirakira
Processing Record 31 of Set 11 : piacabucu
Processing Record 32 of Set 11 : buritis
Processing Record 33 of Set 11 : sobolevo
Processing Record 34 of Set 11 : pangnirtung
Processing Record 35 of Set 11 : puerto escondido
City not found. Skipping...
Processing Record 36 of Set 11 : berlevag
Processing Record 37 of Set 11 : bordighera
Processing Record 38 of Set 11 : nong khai
Processing Record 39 of Set 11 : namibe
Processing Record 40 of Set 11 : coruripe
Processing Record 41 of Set 11 : la paz
Processing Record 42 of Set 11 : buluang
Processing Record 43 of Set 11 : port macquarie
Processing Record 44 of Set 11 : karratha
Processing Record 45 of Set 11 : forrest city
Processing Record 46 of Set 11 : viedma
Processing Record 47 of Set 11 : rush
Processing Record 48 of Set 11 : placido de castro
Processing Record 49 of Set 11 : tarrafal
Processing Record 0 of Set 12 : auki
Processing Record 1 of Set 12 : misratah
Processing Record 2 of Set 12 : shache
Processing Record 3 of Set 12 : esna
Processing Record 4 of Set 12 : grants pass
Processing Record 5 of Set 12 : lasa
Processing Record 6 of Set 12 : sitka
Processing Record 7 of Set 12 : vidim
City not found. Skipping...
Processing Record 8 of Set 12 : praia
Processing Record 9 of Set 12 : balkanabat
Processing Record 10 of Set 12 : zhangye
Processing Record 11 of Set 12 : lompoc
-----------------------------
Data Retrieval Complete

### Convert Raw Data to DataFrame
* Export the city data into a .csv.
* Display the DataFrame

In [4]:
weatherpy_df = pd.DataFrame({"City": city_name,
                            "Latitude": lat,
                            "Longitude": long,
                            "Maximum Temperature": max_temp,
                            "Humidity": humidity,
                            "Cloudiness": cloudiness,
                            "Wind Speed": wind_speed,
                            "Country": country,
                            "Date": date})
weatherpy_df.head()

,City,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,Asău,46.4333,26.4000,52.00,66,90,2.30,RO,1618846284
1,Cape Town,-33.9258,18.4232,71.60,49,20,11.50,ZA,1618846119
2,Yangi Marg`ilon,40.4272,71.7189,69.80,28,100,2.30,UZ,1618846284
3,Plover,44.4564,-89.5440,39.00,60,90,14.97,US,1618846285
4,Aswān,24.0934,32.9070,99.14,15,96,12.57,EG,1618846285

In [7]:
weatherpy_df.describe()

,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Date
count,562.000000,562.000000,562.000000,562.000000,562.000000,562.000000,5.620000e+02
mean,17.980006,21.458099,62.225961,63.791815,50.542705,8.344911,1.618846e+09
std,33.817701,90.628820,22.959258,23.225725,37.933789,5.221229,7.791200e+01
min,-54.800000,-179.166700,-13.450000,3.000000,0.000000,0.600000,1.618846e+09
25%,-11.178675,-57.818675,49.162500,50.000000,14.250000,4.365000,1.618846e+09
50%,22.376100,24.746850,65.120000,67.000000,43.500000,6.910000,1.618846e+09
75%,46.419325,103.103775,79.897500,83.000000,90.000000,11.500000,1.618846e+09
max,78.218600,179.316700,109.400000,100.000000,100.000000,26.870000,1.618846e+09

In [6]:
weatherpy_df.to_csv("../output_data/city.csv")

## Inspect the data and remove the cities where the humidity > 100%.
----
Skip this step if there are no cities that have humidity > 100%.

In [8]:
#  Get the indices of cities that have humidity over 100%.
high_humidity = weatherpy_df.loc[weatherpy_df['Humidity'] >= 100]
high_humidity

,City,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
52,Kwinana,-32.2500,115.7667,62.01,100,42,6.96,AU,1618846301
59,Ancud,-41.8697,-73.8203,54.00,100,75,7.70,CL,1618846304
87,Valdivia,-39.8142,-73.2459,59.00,100,90,10.36,CL,1618846312
90,East London,-33.0153,27.9116,62.60,100,90,10.36,ZA,1618846313
112,Bonavista,48.6499,-53.1147,42.80,100,100,3.44,CA,1618846320
143,Tiksi,71.6872,128.8694,-6.70,100,49,4.34,RU,1618846330
180,Fortuna,40.5982,-124.1573,44.60,100,90,6.91,US,1618846343
369,Saskylakh,71.9167,114.0833,-13.45,100,86,4.14,RU,1618846400
372,Verkhnevilyuysk,63.4453,120.3167,-4.67,100,70,0.69,RU,1618846401
479,Kahului,20.8947,-156.4700,66.00,100,1,6.91,US,1618846435

In [13]:
# Make a new DataFrame equal to the city data to drop all humidity outliers by index.
# Passing "inplace=False" will make a copy of the city_data DataFrame, which we call "clean_city_data".
clean_city_data = weatherpy_df.loc[weatherpy_df['Humidity'] != 100]
clean_city_data.head()

,City,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Country,Date
0,Asău,46.4333,26.4000,52.00,66,90,2.30,RO,1618846284
1,Cape Town,-33.9258,18.4232,71.60,49,20,11.50,ZA,1618846119
2,Yangi Marg`ilon,40.4272,71.7189,69.80,28,100,2.30,UZ,1618846284
3,Plover,44.4564,-89.5440,39.00,60,90,14.97,US,1618846285
4,Aswān,24.0934,32.9070,99.14,15,96,12.57,EG,1618846285
...,...,...,...,...,...,...,...,...,...
557,Vidim,56.4088,103.1106,20.93,84,87,18.37,RU,1618846459
558,Praia,14.9215,-23.5087,80.60,50,20,23.02,CV,1618846460
559,Balkanabat,39.5108,54.3671,73.54,37,31,9.71,TM,1618846460
560,Zhangye,38.9342,100.4517,53.40,36,54,4.38,CN,1618846461
561,Lompoc,34.6391,-120.4579,61.00,93,0,6.91,US,1618846461

In [11]:
clean_city_data.describe()

,Latitude,Longitude,Maximum Temperature,Humidity,Cloudiness,Wind Speed,Date
count,552.000000,552.000000,552.000000,552.000000,552.000000,552.000000,5.520000e+02
mean,17.997320,21.799478,62.689855,63.135870,50.202899,8.384112,1.618846e+09
std,33.550162,90.295544,22.537184,22.912871,37.992245,5.245645,7.836804e+01
min,-54.800000,-179.166700,-11.510000,3.000000,0.000000,0.600000,1.618846e+09
25%,-10.786575,-57.581450,50.000000,50.000000,13.750000,4.380000,1.618846e+09
50%,22.376100,24.746850,66.200000,66.500000,42.500000,6.910000,1.618846e+09
75%,46.344325,102.645825,80.050000,82.000000,90.000000,11.500000,1.618846e+09
max,78.218600,179.316700,109.400000,99.000000,100.000000,26.870000,1.618846e+09

## Plotting the Data
* Use proper labeling of the plots using plot titles (including date of analysis) and axes labels.
* Save the plotted figures as .pngs.

## Latitude vs. Temperature Plot

## Latitude vs. Humidity Plot

## Latitude vs. Cloudiness Plot

## Latitude vs. Wind Speed Plot

## Linear Regression

####  Northern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Southern Hemisphere - Max Temp vs. Latitude Linear Regression

####  Northern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Humidity (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Southern Hemisphere - Cloudiness (%) vs. Latitude Linear Regression

####  Northern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression

####  Southern Hemisphere - Wind Speed (mph) vs. Latitude Linear Regression